<?php
// Set doctype explicitly if it is not `HTML4_LOOSE`, i.e. 'HTML 4.01 Transitional'
$this->doctype('HTML5');

// Load translation data
$this->i18nTheme();

//HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
$this->js(array(
    pi::url('static/js/html5shiv.js') => array(
        'conditional' => 'lt IE 9'
    ),
    pi::url('static/js/respond.min.js') => array(
        'conditional' => 'lt IE 9'
    ),
));

// Load jQuery
$this->jquery();

// Load Bootstrap css/js and font-awesome
$this->bootstrap(array(
    'js/bootstrap.min.js',
    'font-awesome/css/font-awesome.min.css'
));

// Load front.css
$this->css($this->assetTheme('css/front.css'));

// Load localization css
$this->css($this->assetLocale('locale.css'));

// Load front.js on footer
$this->footScript()->appendFile($this->assetTheme('js/jquery.parallax.min.js'));
$this->footScript()->appendFile($this->assetTheme('js/front.js'));

// Apple icons
// Apple icon for iphone
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'href'  => $this->assetTheme('image/touch-icon-iphone.png')
));
// Apple icon for ipad
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'sizes' => '72x72',
    'href'  => $this->assetTheme('image/touch-icon-ipad.png')
));
// Apple icon for iphone retina
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'sizes' => '114x114',
    'href'  => $this->assetTheme('image/touch-icon-iphone-retina.png')
));
// Apple icon for ipad retina
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'sizes' => '114x114',
    'href'  => $this->assetTheme('image/touch-icon-ipad-retina.png')
));

// Meta Viewport Tag
$this->headMeta('width=device-width, initial-scale=1.0', 'viewport');

// Explicitly load favicon
$this->headLink(array(
    'rel'   => 'shortcut icon',
    'type'  => 'image/x-icon',
    'href'  => $this->favicon(),
));
$this->headLink(array(
    'rel'   => 'shortcut icon',
    'type'  => 'image/png',
    'href'  => $this->favicon('favicon.png'),
));

// Load google analytics code
$this->ga();

// Get module name
$module = Pi::service('module')->current();

// Get navigation
$navigation = $this->nav('front');

// Get block
$blocks = $this->blocks();
$blockTemplate = $this->template('block');

// Get breadcrumbs
$breadcrumbs = $this->breadcrumb(
    array('prefix' => array(
        array(
            'label' => __('Home'),
            'href' => Pi::url($this->url('home'))
        )
    ))
);
?>
<!DOCTYPE HTML>
<html lang="<?php echo $locale; ?>">
<head>
    <meta charset="<?php echo $charset; ?>">
    <!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=edge"><![endif]-->
</head>
<body id="pi-<?php echo $module; ?>" class="pi-locale-<?php echo $locale; ?> pi-front" data-spy="scroll" data-target=".navbar-fixed-top" class="top">
<nav class="navbar navbar-custom navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" data-toggle="collapse" data-target=".navbar-main-collapse" class="navbar-toggle">
                <i class="fa fa-bars"></i>
            </button>
            <a href="#page-top" class="navbar-brand page-scroll">
                <img class="img-responsive logo" src="<?php echo $this->assetTheme('image/logo.png'); ?>" alt="<?php echo _escape($sitename); ?>">
            </a>
        </div>
        <div class="collapse navbar-collapse navbar-main-collapse">
            <?php echo $navigation->menu()->setUlClass('nav navbar-nav navbar-left pi-navbar-nav clearfix'); ?>
        </div>
    </div>
</nav>
<header class="pi-header pi-header-half">
    <div class="pi-header-body">
        <?php if ($module == 'system') { ?>
            <h1 class="classic">
                <img src="<?php echo $this->assetTheme('image/header-center.png'); ?>" alt="<?php echo _escape($sitename); ?>">
            </h1>
        <?php } else { ?>
            <h2 class="classic">
                ByUs, Think out of box
            </h2>
        <?php } ?>
    </div>
</header>
<?php if ($module == 'system') { ?>
    <section class="pi-section">
        <div class="pi-section-process clearfix">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-10 col-md-offset-1 col-xs-12">
                        <div class="pi-section-title">
                            <h2 class="no-span">فرآیند ما</h2>
                        </div>
                        <div class="pi-section-body pi-section-icon clearfix text-center">
                            <div class="col-md-3 col-xs-12 pi-section-box-divider">
                                <img class="img-responsive" src="<?php echo $this->assetTheme('image/pi-section-process-1.png'); ?>" alt="">
                                <h3>مشاوره</h3>
                                <h4>Consultation</h4>
                            </div>
                            <div class="col-md-3 col-xs-12 pi-section-box-divider">
                                <img class="img-responsive" src="<?php echo $this->assetTheme('image/pi-section-process-2.png'); ?>" alt="">
                                <h3>نیازسنجی</h3>
                                <h4>Needs Assessment</h4>
                            </div>
                            <div class="col-md-3 col-xs-12 pi-section-box-divider">
                                <img class="img-responsive" src="<?php echo $this->assetTheme('image/pi-section-process-3.png'); ?>" alt="">
                                <h3>ایده پردازی</h3>
                                <h4>Idea making</h4>
                            </div>
                            <div class="col-md-3 col-xs-12">
                                <img class="img-responsive" src="<?php echo $this->assetTheme('image/pi-section-process-4.png'); ?>" alt="">
                                <h3>اجرا</h3>
                                <h4>Performance</h4>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="pi-section-about clearfix">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-10 col-md-offset-1 col-xs-12">
                        <div class="pi-section-body clearfix">
                            <div class="col-md-7 col-xs-12">
                                <h2>درباره بایاس</h2>
                                <p>شما برای خلاقیت، برای یک تفکر خارج از چارچوب و برای نگاهی نو در کسب و کارتان سرمایه گذاری می کنید.<br>
                                    ما در این سرمایه گذاری همراه شما خواهیم بود و تلاش خواهیم کرد با برگزاری جلسات مشاوره، نیاز های شما را به درستی تشخیص داده و پس از ایده پردازی در باره برند شما به اجرای نیاز های تحلیل شدتان بپردازیم. ما در بایاس معتقدیم "طراحی، چیزی نیست که دیده می شه، طراحی اون چیزیه که کار می کنه!"<br>
                                    بر اساس این باور قبل از شروع فرایند طراحی به انجام تحقیقات بازار و بررسی و تدوین استرتژی های شما خواهیم پرداخت تا بتوانیم جایگاهی متفاوت و ماندگار برای برند شما در ذهن مشتریانتان  بسازیم.</p>
                            </div>
                            <div class="col-md-5 col-xs-12 text-center">
                                <img class="img-responsive" src="<?php echo $this->assetTheme('image/pi-section-about.jpg'); ?>" alt="">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="pi-section-service clearfix">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-10 col-md-offset-1 col-xs-12">
                        <div class="pi-section-title">
                            <h2 class="no-span">خدمات</h2>
                        </div>
                        <div class="pi-section-body pi-section-icon clearfix text-center">
                            <div class="col-md-3 col-xs-12">
                                <img class="img-responsive" src="<?php echo $this->assetTheme('image/pi-section-service-1.png'); ?>" alt="">
                                <h3>برندینگ</h3>
                                <h4>Branding</h4>
                            </div>
                            <div class="col-md-3 col-xs-12">
                                <img class="img-responsive" src="<?php echo $this->assetTheme('image/pi-section-service-2.png'); ?>" alt="">
                                <h3>تبلیغات</h3>
                                <h4>Advertisement</h4>
                            </div>
                            <div class="col-md-3 col-xs-12">
                                <img class="img-responsive" src="<?php echo $this->assetTheme('image/pi-section-service-3.png'); ?>" alt="">
                                <h3>دیجیتال مارکتینگ</h3>
                                <h4>Digital marketing</h4>
                            </div>
                            <div class="col-md-3 col-xs-12">
                                <img class="img-responsive" src="<?php echo $this->assetTheme('image/pi-section-service-4.png'); ?>" alt="">
                                <h3>موشن گرافیک</h3>
                                <h4>Motion Graphics</h4>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="pi-section-portfolio clearfix">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12 col-xs-12">
                        <div class="pi-section-title text-center">
                            <h2>نمونه کارها</h2>
                            <h3 class="small">All copyright received 2017 - IRAN - TEHRAN</h3>
                        </div>
                        <div class="pi-section-body clearfix text-center">
                            <div class="col-md-3 col-xs-12">
                                <div class="row">
                                    <a href="" title="">
                                        <img class="img-responsive" src="<?php echo $this->assetTheme('image/pi-section-portfolio-1.jpg'); ?>" alt="">
                                    </a>
                                </div>
                            </div>
                            <div class="col-md-3 col-xs-12">
                                <div class="row">
                                    <a href="" title="">
                                        <img class="img-responsive" src="<?php echo $this->assetTheme('image/pi-section-portfolio-2.jpg'); ?>" alt="">
                                    </a>
                                </div>
                            </div>
                            <div class="col-md-3 col-xs-12">
                                <div class="row">
                                    <a href="" title="">
                                        <img class="img-responsive" src="<?php echo $this->assetTheme('image/pi-section-portfolio-3.jpg'); ?>" alt="">
                                    </a>
                                </div>
                            </div>
                            <div class="col-md-3 col-xs-12">
                                <div class="row">
                                    <a href="" title="">
                                        <img class="img-responsive" src="<?php echo $this->assetTheme('image/pi-section-portfolio-4.jpg'); ?>" alt="">
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="pi-section-divider-1 clearfix">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-10 col-md-offset-1 col-xs-12">
                        <p>WE BELIEVE OUR WORK SPEAKS FOR ITSELF</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="pi-section-help clearfix">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-10 col-md-offset-1 col-xs-12">
                        <div class="pi-section-body clearfix">
                            <div class="col-md-7 col-xs-12">
                                <h2>چگونه میتوانیم به شما کمک کنیم ؟</h2>
                                <p>در دنیای امروز هیچ برندی بدون داشتن استراتژی های مشخص در کسب و کار آنلاین، برنامه ی استراتژیک کاملی نخواهد داشت. تیم متخصص بایاس در کنار شما خواهند بود تا ضمن تدوین برنامه برند شما در فضای آنلاین، طراحی های مورد نیاز شما برای بازاریابی آنلاین را برای شما فراهم کند و از طریق به روز ترین روش های دیجیتال مارکتینگ، مخاطبان  مضاعفی را از دریای بی انتهای اینترنت به سمت برند شما جذب کند.</p>
                            </div>
                            <div class="col-md-5 col-xs-12 text-center">
                                <img class="img-responsive" src="<?php echo $this->assetTheme('image/pi-section-about.jpg'); ?>" alt="">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="pi-section-newsletter clearfix">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-10 col-md-offset-1 col-xs-12">
                        <div class="pi-section-title">
                            <h2 class="no-span">خبرنامه</h2>
                        </div>
                        <div class="pi-section-body clearfix text-center">
                            <p>برای باخبر شدن از آخرین خبر های استدیو بایاس، عضو خبرنامه شوید</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="pi-section-blog clearfix">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-10 col-md-offset-1 col-xs-12">
                        <div class="pi-section-title">
                            <div class="pi-section-title">
                                <h2 class="no-span">وبلاگ</h2>
                            </div>
                        </div>
                        <div class="pi-section-body clearfix">

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="pi-section-count clearfix">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-10 col-md-offset-1 col-xs-12">
                        <div class="pi-section-body clearfix text-center">
                            <div class="col-md-4 col-xs-12">
                                <div class="pi-section-count-number">540</div>
                                <div class="pi-section-count-title">پروژه های تکمیل شده</div>
                            </div>
                            <div class="col-md-4 col-xs-12">
                                <div class="pi-section-count-number">150</div>
                                <div class="pi-section-count-title">مشتریان</div>
                            </div>
                            <div class="col-md-4 col-xs-12">
                                <div class="pi-section-count-number">35</div>
                                <div class="pi-section-count-title">جوایز</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="pi-section-why clearfix">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-10 col-md-offset-1 col-xs-12">
                        <div class="pi-section-title">
                            <h2 class="no-span">Why By Us ?</h2>
                        </div>
                        <div class="pi-section-body pi-section-icon clearfix text-center">
                            <div class="col-md-3 col-xs-12">
                                <img class="img-responsive" src="<?php echo $this->assetTheme('image/pi-section-why-1.png'); ?>" alt="">
                                <h3>تفکر خارج از چهارچوب</h3>
                                <p>استودیو بایاس، با شعار Thinking Outside the Box و با ارائه ی راهکار های نوآورنه ،سعی در برآورده کردن نیازهای مشتریان خود ، به شیوه ای خلاقانه و مدرن را دارد.</p>
                            </div>
                            <div class="col-md-3 col-xs-12">
                                <img class="img-responsive" src="<?php echo $this->assetTheme('image/pi-section-why-2.png'); ?>" alt="">
                                <h3>همکاری آسان</h3>
                                <p>جلب اعتماد مشتریان و ایجاد فضای همکاری حرفه ای و در عین حال دوستانه، از نکات اصلی همکاری با استودیو بایاس بشمار میرود .</p>
                            </div>
                            <div class="col-md-3 col-xs-12">
                                <img class="img-responsive" src="<?php echo $this->assetTheme('image/pi-section-why-3.png'); ?>" alt="">
                                <h3>نیازسنجی همه جانبه</h3>
                                <p>بررسی و آنالیز همه جانبه ی نیاز مشتریان ما در حوزه ی برندینگ ، بازاریابی، تبلیغات و طراحی هویت بصری و ارائه ی محصولات و راهکارهای متناسب برای هر برند، از دلایل همکاری طولانی مدت مشتریان با ماست.</p>
                            </div>
                            <div class="col-md-3 col-xs-12">
                                <img class="img-responsive" src="<?php echo $this->assetTheme('image/pi-section-why-4.png'); ?>" alt="">
                                <h3>موشن گرافیک قوی</h3>
                                <p>بایاس با جمع آوری افرادی خلاق و در حرفه ای ،  دارای یکی از بهترین و موفق ترین تیم های طراحی موشن گرافیک در تهران میباشد.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="pi-section-video clearfix">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-10 col-md-offset-1 col-xs-12">
                        <div class="pi-section-body clearfix text-center"></div>
                    </div>
                </div>
            </div>
        </div>

        <div class="pi-section-customer clearfix">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-10 col-md-offset-1 col-xs-12">
                        <div class="pi-section-title">
                            <div class="pi-section-title">
                                <h2 class="no-span">مشتریان</h2>
                            </div>
                        </div>
                        <div class="pi-section-body clearfix">

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
<?php } else { ?>
    <!-- Page main content: breadcrumb, flash-messenger, blocks and module content -->
    <section class="pi-section">
        <div class="container">
            <div class="pi-main-container">
                <?php if ($breadcrumbs) { echo $breadcrumbs; } ?>
                <!-- Flash messenger -->
                <?php include $this->template('flash-messenger'); ?>
                <!-- Top head zone -->
                <?php if (!empty($blocks['0'])) { ?>
                    <div class="pi-zone-0">
                        <?php foreach ($blocks['0'] as $block) {
                            include $blockTemplate;
                        } ?>
                    </div>
                <?php } ?>
                <div class="row">
                    <!-- Left zone -->
                    <?php if (!empty($blocks['1'])) { ?>
                        <div class="pi-zone-1 col-md-4">
                            <?php foreach ($blocks['1'] as $block) {
                                include $blockTemplate;
                            } ?>
                        </div>
                    <?php } ?>
                    <div class="<?php
                    if (isset($blocks['1']) && isset($blocks['8'])) {
                        echo 'col-md-4';
                    } elseif (isset($blocks['1']) || isset($blocks['8'])) {
                        echo 'col-md-8';
                    } else {
                        echo 'col-md-12';
                    }
                    ?>">
                        <!-- Center top zone -->
                        <?php if (isset($blocks['2'])) { ?>
                            <div class="pi-zone-2">
                                <?php foreach ($blocks['2'] as $block) {
                                    include $blockTemplate;
                                } ?>
                            </div>
                        <?php } ?>
                        <?php if (isset($blocks['3']) || isset($blocks['4'])) { ?>
                            <div class="row">
                                <div class="col-md-6 pi-zone-3">
                                    <?php
                                    if (isset($blocks['3'])) {
                                        foreach ($blocks['3'] as $block) {
                                            include $blockTemplate;
                                        }
                                    }
                                    ?>
                                </div>
                                <div class="col-md-6 pi-zone-4">
                                    <?php
                                    if (isset($blocks['4'])) {
                                        foreach ($blocks['4'] as $block) {
                                            include $blockTemplate;
                                        }
                                    }
                                    ?>
                                </div>
                            </div>
                        <?php } ?>
                        <!-- Module content starts -->
                        <?php if (!empty($content)) { ?>
                            <div class="<?php echo $module; ?>">
                                <div class="pi-module-content" data-ng-app="<?php echo $module; ?>">
                                    <?php echo $content; ?>
                                </div>
                                <?php echo Pi::service('comment')->load(array('options' => array('type' => 'js'))); ?>
                            </div>
                        <?php } ?>
                        <!-- Module content ends -->
                        <?php if (isset($blocks['5']) || isset($blocks['6'])) { ?>
                            <div class="row">
                                <div class="col-md-6 pi-zone-5">
                                    <?php
                                    if (isset($blocks['5'])) {
                                        foreach ($blocks['5'] as $block) {
                                            include $blockTemplate;
                                        }
                                    }
                                    ?>
                                </div>
                                <div class="col-md-6 pi-zone-6">
                                    <?php
                                    if (isset($blocks['6'])) {
                                        foreach ($blocks['6'] as $block) {
                                            include $blockTemplate;
                                        }
                                    }
                                    ?>
                                </div>
                            </div>
                        <?php } ?>
                        <!-- Center bottom zone -->
                        <?php if (isset($blocks['7'])) { ?>
                            <div class="pi-zone-7">
                                <?php foreach ($blocks['7'] as $block) {
                                    include $blockTemplate;
                                } ?>
                            </div>
                        <?php } ?>
                    </div>
                    <!-- Right zone -->
                    <?php if (isset($blocks['8'])) { ?>
                        <div class="col-md-4 pi-zone-8">
                            <?php foreach ($blocks['8'] as $block) {
                                include $blockTemplate;
                            } ?>
                        </div>
                    <?php } ?>
                </div>
                <!-- Bottom foot zone -->
                <?php if (isset($blocks['99'])) { ?>
                    <div class="pi-zone-99">
                        <?php foreach ($blocks['99'] as $block) {
                            include $blockTemplate;
                        } ?>
                    </div>
                <?php } ?>
            </div>
        </div>
    </section>
<?php } ?>
<!-- Footer: sitelink -->
<footer class="pi-footer">
    <?php if ($module == 'system') { ?>
        <div class="pi-footer-contact">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-4 col-md-offset-1 col-xs-12">
                        <h3>تماس با ما</h3>
                        <p>برای آگاهی از شرایط و نحوه ی همکاری با ما، یا ابراز انتقادات انتقادات و پیشنهادات در رابطه با نحوه ی کار کرد استودیو بایاس ، از طریق ایمیل یا ارسال پیام ، با ما در ارتباط باشید.</p>
                        <hr />
                        <ul class="list-unstyled">
                            <li><i class="fa fa-phone"></i> ۰۲۱۸۸۶۶۸۵۹۸</li>
                            <li><i class="fa fa-map-marker"></i> تهران،خیابان مفتح، پایین تر از مطهری، پلاک ۴۲۵</li>
                        </ul>
                    </div>
                    <div class="col-md-4 col-md-offset-1 col-xs-12">
                        <?php echo $this->widget('contact-contact'); ?>
                    </div>
                </div>
            </div>
        </div>
        <div class="pi-footer-map">
            <?php echo $this->googleMap(array(
                'latitude'  => '35.723258',
                'longitude' => '51.428062',
                'zoom'      => '15',
                'title'     => _escape($sitename),
            ),
                '',
                'point',
                array(
                    'htmlClass' => 'pi-footer-map-canvas'
                )); ?>
        </div>
    <?php } ?>
    <div class="pi-footer-body">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-5 col-xs-12">
                    <h4>درباره</h4>
                    <p>شما برای خلاقیت، برای یک تفکر خارج از چارچوب و برای نگاهی نو در کسب و کارتان سرمایه گذاری می کنید.<br>
                        ما در این سرمایه گذاری همراه شما خواهیم بود و تلاش خواهیم کرد با برگزاری جلسات مشاوره، نیاز های شما را به درستی تشخیص داده و پس از ایده پردازی در باره برند شما به اجرای نیاز های تحلیل شدتان بپردازیم. ما در بایاس معتقدیم "طراحی، چیزی نیست که دیده می شه، طراحی اون چیزیه که کار می کنه!"<br>
                        بر اساس این باور قبل از شروع فرایند طراحی به انجام تحقیقات بازار و بررسی و تدوین استرتژی های شما خواهیم پرداخت تا بتوانیم جایگاهی متفاوت و ماندگار برای برند شما در ذهن مشتریانتان  بسازیم.</p>
                </div>
                <div class="col-md-4 col-xs-12">
                    <h4>بایاس</h4>
                    <div class="row">
                        <div class="col-md-6 col-xs-12">
                            <ul class="list-unstyled">
                                <li><a title="http://byus.faragostaresh.ir" href="#">خدمات</a></li>
                                <li><a title="http://byus.faragostaresh.ir" href="#">بلاگ</a></li>
                                <li><a title="http://byus.faragostaresh.ir" href="#">مشتریان</a></li>
                                <li><a title="http://byus.faragostaresh.ir" href="#">نمونه کار ها</a></li>
                            </ul>
                        </div>
                        <div class="col-md-6 col-xs-12">
                            <ul class="list-unstyled">
                                <li><a title="http://byus.faragostaresh.ir" href="#">درباره ما</a></li>
                                <li><a title="http://byus.faragostaresh.ir" href="#">تماس با ما</a></li>
                                <li><a title="http://byus.faragostaresh.ir" href="#">فرصت های شغلی</a></li>
                                <li><a title="http://byus.faragostaresh.ir" href="#">بایاس +</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-md-3 col-xs-12">

                </div>
            </div>
        </div>
    </div>
    <div class="pi-footer-copyright">
        <div class="container-fluid">
            <div class="row">
                <div class="text-left col-md-3 col-xs-12">
                    <div class="pi-footer-social">
                        <ul class="list-inline">
                            <li><a title="" href="#"><i class="fa fa-instagram"></i></a></li>
                            <li><a title="" href="#"><i class="fa fa-twitter"></i></a></li>
                            <li><a title="" href="#"><i class="fa fa-facebook"></i></a></li>
                            <li><a title="" href="#"><i class="fa fa-linkedin"></i></a></li>
                            <li><a title="" href="#"><i class="fa fa-google"></i></a></li>
                        </ul>
                    </div>
                </div>
                <div class="text-center col-md-6 col-xs-12" data-rel="license"> تمام حقوق مطالب برای وب سایت <a title="<?php echo _escape($sitename); ?>" href="http://byus.faragostaresh.ir"><?php echo _escape($sitename); ?></a> محفوظ است.</div>
                <div class="text-right col-md-3 col-xs-12" data-rel="license"> توسعه <a title="فراگسترش" href="http://www.faragostaresh.com" target="_blank">فراگسترش</a> و طراحی <a title="بایاس" href="http://byus.faragostaresh.ir" target="_blank">بایاس</a></div>
            </div>
        </div>
    </div>
</footer>
<?php echo $this->conditions() ?>
</body>
</html>